### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by unparadise** [lgeiger/ide-python#102]
Hi,

I love the ide-python add-on on Max and Windows. It works great! But when I tried to install it on my Ubuntu laptop. It stopped working. Even after I changed the default Python Language Server Path to './home/liangchen/.local/bin/pyls', it still does not work. What am I doing wrong here?

I am using Ubuntu 17.10. Python 3.6.

Thank you for your help in advance.

Cheers,
Frank

**Comment by exploide** [comment]
`./home/liangchen/.local/bin/pyls` as a path is probably wrong, since it looks for a directory called `home/` in the current directory (because you started with `./` where the dot is the current working directory). You probably want this to be `/home/liangchen/.local/bin/pyls`.

However, if your `PATH` environment variable is properly set up and `pyls` is correctly installed, then you don't need to specify this explicitly.

Can you invoke `pyls` from a terminal? If yes, what does `which pyls` and `echo $PATH` say?

**Comment by lgeiger** [comment]
Checkout the release notes of [version 1.0](https://github.com/lgeiger/ide-python/releases/tag/v1.0.0)
