### ISSUE TITLE
# NOQA or analog.

### ISSUE THREAD

**Issue by stavinsky** [lgeiger/ide-python#12]
When using flake8 I can add #NOQA flag and prevent showing errors and warnings for line or file. Here I can't. As I can understand this is because of using pyls that uses pyflakes.  Can we do something exclude exact line from checks?

**Comment by lgeiger** [comment]
You're right, `pyls` uses `pycodestyle` and `pyflakes` to do the linting.

`pycodestyle` only allows [certain errors to be excluded via `  # noqa`](http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes), `pyflakes` doesn't support `  # noqa` at all. This is a deliberate choice of both tools, for more information see https://github.com/PyCQA/pycodestyle/issues/480.

Unfortunately this needs to be fixed upstream.

Since `ide-python v0.2.0` you can disable specific plugins, if that's a total deal-breaker for you. Or you can make a PR to [`pyls`](https://github.com/palantir/python-language-server) to add a `flake8` plugin.

On how to configure `pycodestyle` to ignore certain errors globally, see https://github.com/lgeiger/ide-python/issues/9#issuecomment-329666714.
