### ISSUE TITLE
Pylint support

### ISSUE THREAD

**Issue by willfrey** [lgeiger/ide-python#25]
Please and thank you!

**Comment by lgeiger** [comment]
👍 Once https://github.com/palantir/python-language-server/issues/129 is fixed, we will support it.

**Comment by willfrey** [comment]
Great! Thank you.

**Comment by mscuthbert** [comment]
Might be closer to completion than before, given palantir/python-language-server#202

**Comment by lgeiger** [comment]
This is now fixed in #159 🎉 

This feature requires `pyls` 0.25 or later:
Upgrade by running `python -m pip install 'python-language-server[all]' --upgrade`

Note that due to limitations in Pylint, only files saved to disk are linted.

Please try it out and provide feedback if anything is broken: https://github.com/palantir/python-language-server
