### ISSUE TITLE
Forever formatting loop

### ISSUE THREAD

**Issue by extraymond** [lgeiger/ide-python#44]
Hi! thx for the addon, it's been really useful to me.
However when running on file with hundreds of lines, it stopped working and the showed forever formatting loop.

I've set format on save in atom-ide-ui, so whenever I safe the file, typically it should format on the fly, but after it stopped working, it get all piled up in the task queue and not doing anything.

I'm wondering if this is normal with the python ide server or possible can be handled by the addon. Thx.

**Comment by Larandar** [comment]
I have the same issue on windows, but from what I see not only formating stop working but linter and suggestion too stoped working at some point.

Usually I just restart my editor but it's not great to do it every 5 or 10 saves.

Do you need any help ? Which log can I give you that will help ?

**Comment by extraymond** [comment]
It can be reproduced by constantly saving in a short period(I have formatting on save to True in atom ide ui settings.)

This is lead me to believe it's something to do with task queue issue.

**Comment by mgawin** [comment]
Same here. Happens every couple of saves and requires restart to fix...

**Comment by extraymond** [comment]
I think I found a potential cause.
It's related to hyper link function.

When it's enabled, and you drag across multiple variables, it will stuffed the ide server to death.
Not sure if this is the only cause, but I can trigger the forever loop by clicking this on and off.
I end up using python-tools goto, its not that intuitive, but at least the linter won't crash.

**Comment by lgeiger** [comment]
This sounds like `pyls` is crashing underneath. Which version of `pyls` are you using?

Could you enable debug messages by executing `atom.config.set('core.debugLSP', true)` in the Developer Tools Console and post a screenshot of the console output when this issue occurs? You might need to restart Atom in order to see the debug messages.

**Comment by extraymond** [comment]
@lgeiger  Hi! I'm using plys 0.12.1.

![2017-12-31 00-08-12](https://user-images.githubusercontent.com/707176/34455700-852edff8-edbf-11e7-8867-1a4d157044e0.png)
![2017-12-31 00-11-58](https://user-images.githubusercontent.com/707176/34455701-8782f7a8-edbf-11e7-9eea-b4ff1ade27bb.png)

And here's the log, it seems to indicate something with ide-css and ide-vue, which I uninstalled. But still popped up.

**Comment by lgeiger** [comment]
Thanks for the screenshots! I wonder if the problem is coming from the unicode characters.

Could you provide some example code where formating fails?

**Comment by extraymond** [comment]
Hi! This one is successfully formatted. (which contains non-latin characters.)

![peek 2017-12-31 00-30](https://user-images.githubusercontent.com/707176/34455803-e2102dce-edc1-11e7-861d-4a543d6eaca3.gif)

But this one failed to format the code, I've been using save to format so I've been hitting ctrl-s several times but nothing happened. But the linting is working though which is weird. I thought LSP should handled all the interfaces at once so if linting is working why won't formatting work?

![peek 2017-12-31 00-32](https://user-images.githubusercontent.com/707176/34455825-629466ea-edc2-11e7-9bcb-5f170ce2bcdf.gif)

**Comment by lgeiger** [comment]
> I thought LSP should handled all the interfaces at once so if linting is working why won't formatting work?

It looks like the formating request was completed but `yapf` didn't know how to format it. Therefor linting still works.
You can see the requests if you enable debug messages by executing `atom.config.set('core.debugLSP', true)` in the Developer Tools Console and restarting Atom?

**Comment by extraymond** [comment]
![image](https://user-images.githubusercontent.com/707176/34455903-2787dc7e-edc4-11e7-8b9c-90560ebb1c60.png)

Ah, forgot to turn this on.
So it's throwing error for "rangeFormatting".

**Comment by lgeiger** [comment]
Unfortunately the internal error from pyls doesn't show up in the log. Can you post the content of `paq-flask/project/common/data.py` so I can try and reproduce this error.

**Comment by extraymond** [comment]
@lgeiger  Since it imported some external files and modules, do I have to share those with you too? If so I'm afraid I won't be able to so  since it needs to be approved by peers.

Is that ok I e-mail you just this script?

**Comment by lgeiger** [comment]
> Is that ok I e-mail you just this script?

I guess for formatting the script should be enough: lukas.geiger94@gmail.com

**Comment by lgeiger** [comment]
@extraymond You're running into https://github.com/google/yapf/issues/403 since some of your variable names are unicode characters. Unfortunately we cannot do anything about this on the `ide-python` side.

I also noticed that `yapf` can take a long time for formating code. That's why there may be multiple formatting requests queued up. For long files I wouldn't recommend format on save.
I don't know if there's a better/faster python code formatter to use but you can open a issue on the `python-language-server` and suggest optimisations. The problem with this is that long running formatting requests will block linting and other ls features until they resolve due to the implementation in pyls.

That said I think the `python-language-server` should properly handle the errors instead of throwing a exception. I'm going to open a issue on the pyls repo.

**Comment by extraymond** [comment]
@lgeiger  Thx for sharing this. I'll try replacing vars to be more formal. I'm really thankful for you being both helpful and educational in the end of a year! Wish you a happy holiday.

**Comment by lgeiger** [comment]
The [latest release](https://github.com/lgeiger/ide-python/releases/tag/v0.9.0) supports the `autopep8` formatter. This might help with this issue.
