### ISSUE TITLE
How to make it work on Mac with Python 3?

### ISSUE THREAD

**Issue by unparadise** [lgeiger/ide-python#45]
I have a Mac and I installed Python 3.6.2 from the website. Then I used "pip3 install python-language-server" to install the language server for Python 3. It still doesn't work after that.

**Comment by exploide** [comment]
I assume you have Atom >= 1.21 installed as well as packages `ide-python` and `atom-ide-ui`?!

Can you run `pyls` in terminal? What is the output of `which pyls`?

**Comment by unparadise** [comment]
Hi exploide, thank you for trying to help. Yes, I have Atom 1.22.1, aton-ide-ui, and ide-python installed.

Even though I successfully installed pyls using "pip3 install python-language-server", when I tried to run "plys", the terminal says "pyls: command not found". I looked up on Google where pyls is installed but couldn't find anything.

Thanks,
Frank

**Comment by unparadise** [comment]
Okay, exploide, I installed pip on my Mac and was able to install pyls using "pip install python-language-server". Everything went through. It seems that it's working now. But do you know the difference between pip and pip3? I am writing Python 3 code. Is pip install for Python 2.7?

**Comment by exploide** [comment]
Ok, that sounds like a problem with your path. It should be somewhere, you may find it using `find / -name pyls` or similar methods. I'm not familiar with Mac OS. After that, you can decide if you want to add the directory to your system path variable, so applications installed there can always be found, or you just go to `ide-python` settings and give it the path to `pyls` there.

You can run `pip --version` and it should tell you if it is for Python 2 or Python 3. On most systems and when not inside a virtualenv, pip is usually for python2 and pip3 for python3.

**Comment by kbatbouta** [comment]
**Ok First of all** 😠

a.  Path to Python can be found by running this in python : ( if you don't know )
```
import sys
sys.executable
```  
b.   if you installed Python throw brew than the path is ( probably )
```
/usr/local/share/python
```
Ok now that you know your  **Python path**

on MacOS go to home folder than click shift-command-dot.
than Find file ```/Users/<username>/.bash_profile``` 
open it with any text editor and add  ``` export PATH="<python-folder-path>/bin/:$PATH" ```

> **NOTE**: replace  <python-folder-path> with your python path you found using the above methods

then restart your **Computer** ( I know he cloud just restart the terminal session or Atom ) 

Ok and Finally you are done...

> **NOTE**: but remember you can Google it or even **Bing it** before opening an issue 😉 

this cover only the PATH issue because there it may not work with the latest ```pyls``` which is if I remember correctly ```v0.11.1``` you may need to install  ```v0.8.0``` and have Jedi at version ```0.10.2```

**Comment by lgeiger** [comment]
👍the `pyls` executable needs to be on your `PATH`.
