### ISSUE TITLE
installing python language server

### ISSUE THREAD

**Issue by Airmagic** [lgeiger/ide-python#67]
in the instructions it tell what to do to check if the python language is installed, but doesn't say where you use the pip install or what to do if it didn't work.

**Comment by 7aleb** [comment]
I have been using https://github.com/mitsuhiko/pipsi to manage global python packages
You can try this.

**Comment by exploide** [comment]
README says that you can use `pip install python-language-server` to install it. *Where* you do this depends on your taste. You can install system-wide (then execute with `sudo`), user-wide `providing the `--user` flag or inside a virtualenv.

Since I assume you are new to Python programming, just try `pip3 install --user python-language-server`. The `pip3` is to install this package for Python 3. If you still use Python 2 for whatever reason, use `pip2` instead.

Feel free to ask back if something doesn't work.

**Comment by lgeiger** [comment]
@exploide @7aleb Thanks for helping!

Closing as solved/stale.

@Airmagic Feel free to reopen if you still need help.
