### ISSUE TITLE
Validation for pylsPluginConfiguration is too aggressive

### ISSUE THREAD

**Issue by ediphy-azorab** [lgeiger/ide-python#79]
In preferences, under `Pyls Plugins Configuration Sources`, typing 'py' and waiting for a short period (<1s) will result in the entry being deleted. Looking at the console we get the warning:

```
Error setting item in array: Validation failed at ide-python.pylsPlugins.configurationSources, "py" is not one of ["pycodestyle","pyflakes"]
```

This is probably too aggressive :)

**Comment by lgeiger** [comment]
Thanks for catching this. Unfortunately on our side we can only completely disable the validation.
This is probably a issue in [Atom Core](https://github.com/atom/atom) since it only appears on the first array value:
![settings_enum](https://user-images.githubusercontent.com/13285808/35596847-e4e3f7e8-061b-11e8-85ca-82ea788ddcbe.gif)

Want to file a [issue](https://github.com/atom/atom/issues) there. Feel free to include the above GIF.

**Comment by lgeiger** [comment]
I'm going to close this issue since this is a bug in Atom core.
